DatingApp/Models/DatingRepository.cs
using Newtonsoft.Json;
using System.Collections.Generic;

namespace DatingApp.Models
{
    public class DatingRepository
    {
        [JsonProperty]
        private Dictionary<Gender, Person> personCollection = new Dictionary<Gender, Person>();
        public virtual void AddPerson(Person person)
        {
            var key = person.Gender;
            if (personCollection.ContainsKey(key))
            {
                personCollection[key] = person;
            }
            else
            {
                personCollection.Add(key, person);
            }
        }
        public Person GetPerson(Gender gender)
        {
            return personCollection[gender];
        }
    }
}

DatingApp/Models/Person.cs
using DatingApp.Infrastructure;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DatingApp.Models
{
    public class Person
    {
        [Required(ErrorMessage = "Proszę podać imię")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Proszę podać prawidłową wartość")]
        [Range(0.1, 4, ErrorMessage = "Proszę podać wartość między 0.1 a 4")]
        public double Height { get; set; }
        [Required]
        [UIHint("Date")]
        [MustBeAdult(ErrorMessage = "Osoba musi być pełnoletnia")]
        public DateTime BirthDate { get; set; }
        public EyesColor EyesColor { get; set; }
        public Gender Gender { get; set; }
    }

    public enum Gender
    {
        Female,
        Male
    }

    public enum EyesColor
    {
        [Display(Name = "niebieskie")]
        Blue,
        [Display(Name = "zielone")]
        Green,
        [Display(Name = "piwne")]
        Brown
    }
}

DatingApp/Models/PersonMatcher.cs
using DatingApp.Models.Validators;
using System.Collections.Generic;
using System.Linq;

namespace DatingApp.Models
{
    public class PersonMatcher
    {
        private IEnumerable<IPersonValidator> validators;
        public Person Woman { get; set; }
        public Person Man { get; set; }

        public PersonMatcher(IEnumerable<IPersonValidator> validators)
        {
            this.validators = validators;
        }

        public bool Matched()
        {
            return validators.All(v => v.Matched(Woman, Man));
        }

    }
}

DatingApp/Models/SessionRepository.cs
using DatingApp.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Newtonsoft.Json;
using System;

namespace DatingApp.Models
{
    public class SessionRepository : DatingRepository
    {
        public static DatingRepository GetDatingRepository(IServiceProvider services)
        {
            ISession session = services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;
            SessionRepository repo = session?.GetJson<SessionRepository>("repo") ?? new SessionRepository();
            repo.Session = session;
            return repo;

        }
        [JsonIgnore]
        public ISession Session { get; set; }

        public override void AddPerson(Person person)
        {
            base.AddPerson(person);
            Session.SetJson("repo", this);
        }
    }
}

DatingApp/Models/Validators/AgeValidator.cs
using DatingApp.Infrastructure;
using System;

namespace DatingApp.Models.Validators
{
    public class AgeValidator : IPersonValidator
    {
        private int maxDiff = 5;
        public bool Matched(Person woman, Person man)
        {
            return Math.Abs(man.BirthDate.CountYears() - woman.BirthDate.CountYears()) <= maxDiff;
        }
    }
}

DatingApp/Models/Validators/EyesColorValidator.cs
namespace DatingApp.Models.Validators
{
    public class EyesColorValidator : IPersonValidator
    {
        public bool Matched(Person woman, Person man)
        {
            return man.EyesColor == woman.EyesColor;
        }
    }
}

DatingApp/Models/Validators/HeightValidator.cs
namespace DatingApp.Models.Validators
{
    public class HeightValidator : IPersonValidator
    {
        private int minDiff = 10;
        public bool Matched(Person woman, Person man)
        {
            return ((int)(man.Height * 100) - (int)(woman.Height * 100)) >= minDiff;
        }
    }
}

DatingApp/Models/Validators/IPersonValidator.cs
namespace DatingApp.Models.Validators
{
    public interface IPersonValidator
    {
        bool Matched(Person woman, Person man);
    }
}

DatingApp/Controllers/ManController.cs
using DatingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace DatingApp.Controllers
{
    public class ManController : Controller
    {
        private DatingRepository repo;
        public ManController(DatingRepository repo)
        {
            this.repo = repo;
        }
        public IActionResult Start()
        {
            return View("Person", new Person
            {
                Gender = Gender.Male
            });
        }

        public IActionResult Next(Person person)
        {
            if (!ModelState.IsValid)
            {
                return View("Person", person);
            }

            repo.AddPerson(person);
            return RedirectToAction("Index", "Result");
        }
    }
}

DatingApp/Controllers/ResultController.cs
using DatingApp.Models;
using DatingApp.Models.Validators;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace DatingApp.Controllers
{
    public class ResultController : Controller
    {
        private DatingRepository repo;
        private IEnumerable<IPersonValidator> validators;
        public ResultController(DatingRepository repo, IEnumerable<IPersonValidator> validators)
        {
            this.repo = repo;
            this.validators = validators;
        }
        public ViewResult Index()
        {
            return View(new PersonMatcher(validators)
            {
                Woman = repo.GetPerson(Gender.Female),
                Man = repo.GetPerson(Gender.Male)
            });
        }
    }
}

DatingApp/Controllers/WomanController.cs
using DatingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace DatingApp.Controllers
{
    public class WomanController : Controller
    {
        private DatingRepository repo;
        public WomanController(DatingRepository repo)
        {
            this.repo = repo;
        }
        public IActionResult Start()
        {
            return View("Person", new Person
            {
                Gender = Gender.Female
            });
        }

        public IActionResult Next(Person person)
        {
            if (!ModelState.IsValid)
            {
                return View("Person", person);
            }

            repo.AddPerson(person);
            ModelState.Clear();

            return RedirectToAction("Start", "Man");
        }
    }
}

DatingApp/Views/Result/Index.cshtml
@model PersonMatcher

<h1>Wynik</h1>
<div class="text-center">
    <p class="h4">@Model.Man.Name</p>
    <p class="h4 ">i</p>
    <p class="h4">@Model.Woman.Name</p>
    <p class="h4">@(Model.Matched() ? "pasują" : "nie pasują")</p>
    <p class="h4">do siebie</p>
</div>
<form asp-action="Start" asp-controller="Woman">
    <button type="submit" class="btn btn-primary">Od nowa</button>
</form>

DatingApp/Views/Shared/Person.cshtml
@model Person

<h1>@(Model.Gender == Gender.Female ? "Kobieta" : "Mężczyzna")</h1>
<form asp-action="Next" method="post">
    <div class="form-group">
        @Html.LabelFor(model => model.Name, "Imię")
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Height, "Wzrost")
        @Html.TextBoxFor(m => m.Height, new { @class = "form-control" })
        <small class="form-text text-muted">
            Proszę podać wzrost w metrach
        </small>
        <span asp-validation-for="Height" class="text-danger"></span>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.BirthDate, "Data urodzenia")
        @Html.TextBoxFor(m => m.BirthDate, new { @class = "form-control" , @type = "date"})
        <span asp-validation-for="BirthDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.BirthDate, "Kolor oczu")
        @Html.DropDownListFor(m => m.EyesColor, Html.GetEnumSelectList<EyesColor>(), new { @class = "form-control" })
    </div>
    <input type="hidden" asp-for="Gender" value="@Model.Gender" />
    <button type="submit" class="btn btn-primary">Dalej</button>
</form>

DatingApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DatingApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - DatingApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>